config/routes.rb
Spree::Core::Engine.routes.draw do
  # Add your extension routes here
  Spree::Core::Engine.routes.draw do
    get "/adlogica_extension_installed" => "adlogica#is_configured"
  end
  namespace :admin do
    resource :adlogica_settings do
      collection do
        post :dismiss_alert
      end
    end
  end
end

app/models/spree/adlogica_configuration.rb
module Spree
  class AdlogicaConfiguration < Preferences::Configuration
    preference :org_id, :string, :default => ""
    preference :app_id, :string, :default => ""
  end
end

app/controllers/spree/adlogica_controller.rb
class Spree::AdlogicaController < Spree::StoreController
    def is_configured
      @store = current_store
      if @store.org_id.empty? || @store.app_id.empty?
	respond_to do |format|
          format.json { render json: {"is_configured" => false, "is_installed" => true }, status: 200 }
        end
      else
        respond_to do |format|
          format.json { render json: {"is_configured" => true, "is_installed" => true }, status: 200 }	
        end
      end
    end
end

app/controllers/spree/admin/adlogica_settings_controller.rb
require 'spree'
require 'spree/core/controller_helpers/store'
module Spree
  module Admin
    class AdlogicaSettingsController < Spree::Admin::BaseController
      before_filter :set_store
      include Spree::Core::ControllerHelpers::Store

      def edit
      end

      def update
        params.each do |name, value|
          next unless Spree::Config.has_preference? name
          Spree::Config[name] = value
        end
	current_store.update_attributes store_params
	
        flash[:success] = Spree.t(:successfully_updated, :resource => Spree.t(:adlogica_settings))
        redirect_to edit_admin_adlogica_settings_path
      end

      def dismiss_alert
        if request.xhr? and params[:alert_id]
          dismissed = Spree::Config[:dismissed_spree_alerts] || ''
          Spree::Config.set :dismissed_spree_alerts => dismissed.split(',').push(params[:alert_id]).join(',')
          filter_dismissed_alerts
          render :nothing => true
        end
      end

      private
      def store_params
        params.require(:store).permit(permitted_params)
      end

      def permitted_params
        return [:org_id, :app_id]  
      end

      def set_store
        @store = current_store
      end
    end
  end
end

app/views/spree/adlogica/is_configured.html.erb
<div>
  <%= @installed %>
</div>

app/views/spree/admin/adlogica_settings/edit.html.erb
<%= render :partial => 'spree/admin/shared/configuration_menu' %>
<% content_for :page_title do %>
  <%= Spree.t(:adlogica_settings) %>
<% end %>

<%= form_tag admin_adlogica_settings_path, :method => :put do %>
    <div id="preferences" data-hook>

    <fieldset class="general no-border-top">

      <%= fields_for :store do |f| %>
        <div class="field">
          <%= f.label :org_id, "Organization ID" %>
          <br />
          <%= f.text_field :org_id %>
        </div>
        <div class="field">
          <%= f.label :app_id, "Application ID" %>
          <br />
          <%= f.text_field :app_id %>
        </div>

      <% end %>


      <div class="form-buttons filter-actions actions" data-hook="buttons">
        <%= button Spree.t('actions.update'), 'refresh' %>
        <span class="or"><%= Spree.t(:or) %></span>
        <%= link_to_with_icon 'remove', Spree.t('actions.cancel'), edit_admin_adlogica_settings_url, :class => 'button' %>
      </div>

    </fieldset>

  </div>
<% end %>

app/views/spree/admin/shared/_adlogica_configuration_menu.html.erb
<%= configurations_sidebar_menu_item Spree.t(:adlogica_settings), edit_admin_adlogica_settings_path %>